# Default values for kubeflow-pipelines.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Override Kubernetes version
kubeVersion: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Annotations to add to all deployed objects
commonAnnotations: {}

# Labels to add to all deployed objects
commonLabels: {}

kubeflow:
  # Enable integration with Kubeflow
  enabled: false

  # Istio gateway name
  gatewayName: kubeflow

cacheDeployer:
  replicaCount: 1

  image:
    repository: gcr.io/ml-pipeline/cache-deployer
    tag: 1.7.0
    pullPolicy: IfNotPresent

  pdb:
    # Specifies whether a pod disruption budget should be created
    create: false

    # Minimum number/percentage of pods that should remain scheduled
    minAvailable: 1

    # Maximum number/percentage of pods that may be made unavailable
    # maxUnavailable: 1

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name:

  # Additional pod annotations
  podAnnotations: {}

  # Additional pod labels
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  # Priority class name
  # priorityClassName : high-priority

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  extraArgs: {}
    # name: ""

  # Additional container environment variables
  extraEnvVars: []
  #  - name: MY-NAME
  #    value: "MY-VALUE"

  # Name of existing ConfigMap containing additional container environment variables
  extraEnvVarsCM:

  # Name of existing Secret containing additional container environment variables
  extraEnvVarsSecret:

cacheServer:
  replicaCount: 1

  image:
    repository: gcr.io/ml-pipeline/cache-server
    tag: 1.7.0
    pullPolicy: IfNotPresent

  pdb:
    # Specifies whether a pod disruption budget should be created
    create: false

    # Minimum number/percentage of pods that should remain scheduled
    minAvailable: 1

    # Maximum number/percentage of pods that may be made unavailable
    # maxUnavailable: 1

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name:

  # Additional pod annotations
  podAnnotations: {}

  # Additional pod labels
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  # Priority class name
  # priorityClassName : high-priority

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    # Service annotations
    annotations: {}

    # Service type
    type: ClusterIP

    # Static cluster IP address or None for headless service when service type is ClusterIP
    # clusterIP: 10.43.0.100

    # Static load balancer IP address when service type is LoadBalancer
    # loadBalancerIP: 10.0.0.100

    # Source IP address ranges when service type is LoadBalancer
    # loadBalancerSourceRanges:
    #   - 10.0.0.0/24

    # External traffic routing policy when service type is LoadBalancer or NodePort
    externalTrafficPolicy: Cluster

    # Service port
    port: 443

    # Service node port when service type is LoadBalancer or NodePort
    # nodePort: 30000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  extraArgs: {}
    # name: ""

  # Additional container environment variables
  extraEnvVars: []
  #  - name: MY-NAME
  #    value: "MY-VALUE"

  # Name of existing ConfigMap containing additional container environment variables
  extraEnvVarsCM:

  # Name of existing Secret containing additional container environment variables
  extraEnvVarsSecret:

mariadb:
  # Whether to use the MariaDB chart
  enabled: true

  # MariaDB architecture
  architecture: standalone

  auth:
    # MariaDB database
    database: kubeflow-pipelines

    # MariaDB user
    username: kubeflow-pipelines

    # MariaDB password
    password: kubeflow-pipelines

    # Name of existing Secret to use
    existingSecret: ""

  primary:
    # Additional pod annotations for MariaDB primary pods
    podAnnotations:
      sidecar.istio.io/inject: "false"

    service:
      # MariaDB port
      port: 3306

  secondary:
    # Additional pod annotations for MariaDB secondary pods
    podAnnotations:
      sidecar.istio.io/inject: "false"

externalMariadb:
  # Whether to use an external MariaDB
  enabled: false

  # External MariaDB host
  host: mariadb

  # External MariaDB port
  port: 3306

  # External MariaDB user
  username: kubeflow-pipelines

  # External MariaDB password
  password: kubeflow-pipelines

  # Name of existing Secret to use
  existingSecret: ""

  # Name of the key in existing Secret that contains MariaDB password
  existingSecretKeyPassword: mariadb-password

  # External MariaDB database
  database: kubeflow-pipelines

tests:
  image:
    # Image name
    repository: ghcr.io/cowboysysop/pytest

    # Image tag
    tag: 1.0.0

    # Image pull policy
    pullPolicy: IfNotPresent
