{{- if .Values.admissionController.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jitsi-meet.admissionController.serviceAccountName" . }}
  labels:
    {{- include "jitsi-meet.admissionController.labels" . | nindent 4 }}
  {{- with .Values.admissionController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
