apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubeflow.katib.controller.fullname" . }}
  labels:
    {{- include "kubeflow.katib.controller.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kubeflow.katib.controller.fullname" . }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ include "kubeflow.katib.controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-experiment
        port: {{ .Values.katib.controller.service.port }}
    name: validate-experiment.controller.katib.kubeflow.org
    rules:
      - apiGroups:
          - kubeflow.org
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - experiments
    sideEffects: None
