{{- if (not .Values.jigasi.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.jigasi.secretName" . }}
  labels:
    {{- include "jitsi-meet.jigasi.labels" . | nindent 4 }}
type: Opaque
data:
  xmpp-password: {{ default (randAlphaNum 32) .Values.jigasi.xmppPassword | b64enc | quote }}
{{- end }}
