apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.admissionController.replicaCount }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.admissionController.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vertical-pod-autoscaler.admissionController.selectorLabels" . | nindent 8 }}
        {{- with .Values.admissionController.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/admission-controller/tls-secret.yaml") . | sha256sum }}
        {{- with .Values.admissionController.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "vertical-pod-autoscaler.admissionController.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.admissionController.podSecurityContext | nindent 8 }}
      containers:
        - name: admission-controller
          securityContext:
            {{- toYaml .Values.admissionController.securityContext | nindent 12 }}
          image: "{{ .Values.admissionController.image.repository }}:{{ .Values.admissionController.image.tag }}"
          imagePullPolicy: {{ .Values.admissionController.image.pullPolicy }}
          args:
            - --client-ca-file=/tls-secret/ca.crt
            - --tls-cert-file=/tls-secret/tls.crt
            - --tls-private-key=/tls-secret/tls.key
            {{- range $key, $value := .Values.admissionController.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: https
              containerPort: 8000
              protocol: TCP
            - name: http-metrics
              containerPort: 8944
              protocol: TCP
          {{- if .Values.admissionController.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: http-metrics
            initialDelaySeconds: {{ .Values.admissionController.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.admissionController.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.admissionController.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.admissionController.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.admissionController.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.admissionController.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: http-metrics
            initialDelaySeconds: {{ .Values.admissionController.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.admissionController.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.admissionController.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.admissionController.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.admissionController.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.admissionController.resources | nindent 12 }}
          volumeMounts:
            - name: tls-secret
              mountPath: /tls-secret
              readOnly: true
      {{- with .Values.admissionController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.admissionController.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.admissionController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ include "vertical-pod-autoscaler.admissionController.tls.secretName" . }}
