apiVersion: v1
kind: Service
metadata:
  # name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  name: vpa-webhook
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admissionController.service.type }}
  ports:
    # - port: {{ .Values.admissionController.service.port }}
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "vertical-pod-autoscaler.admissionController.selectorLabels" . | nindent 4 }}
