apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "kubeflow.fullname" . }}
  labels:
    {{- include "kubeflow.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  servers:
    - port:
        number: 80
        protocol: HTTP
        name: http
      hosts:
        - "*"
  selector:
    {{- toYaml .Values.istioSelector | nindent 4 }}
