apiVersion: v2
appVersion: [[ application.appVersion ]]
[% set description = application.description | regex_replace(".*<<", "") | regex_replace(">>.*", "") %]
description: [[ description[0] | upper ]][[ description[1:] ]]
home: [[ application.home ]]
[% if application.icon %]
icon: [[ application.icon ]]
[% endif %]
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: [[ application.name ]]
sources:
  - [[ application.source ]]
  - https://github.com/cowboysysop/charts/tree/master/charts/[[ application.name ]]
version: [[ application.version ]]
dependencies:
  - name: common
    version: 2.9.0
    repository: https://charts.bitnami.com/bitnami/
  [% if application.mariadb %]
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami/
    condition: mariadb.enabled
  [% endif %]
  [% if application.mongodb %]
  - name: mongodb
    version: 13.16.0
    repository: https://charts.bitnami.com/bitnami/
    condition: mongodb.enabled
  [% endif %]
  [% if application.postgresql %]
  - name: postgresql
    version: 12.11.1
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  [% endif %]
  [% if application.redis %]
  - name: redis
    version: 17.13.2
    repository: https://charts.bitnami.com/bitnami/
    condition: redis.enabled
  [% endif %]
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=[[ application.kubeMinVersion or "1.24" ]]"
