# Default values for [[ application.name ]].
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # Global Docker image registry
  imageRegistry: ""

  # Global Docker registry secret names as an array
  imagePullSecrets: []

# Override Kubernetes version
kubeVersion: ""

nameOverride: ""
fullnameOverride: ""

# Annotations to add to all deployed objects
commonAnnotations: {}

# Labels to add to all deployed objects
commonLabels: {}

# Array of extra objects to deploy with the release
extraDeploy: []
[%- for component in application.components %]
[[ "" ]]
# Number of replicas[%- if component.deployment.volumes and component.deployment.volumes.data %] (do not change it)[%- endif %]
replicaCount: 1
[%- if component.deployment.volumes and component.deployment.volumes.data %]

updateStrategy:
  # Update strategy type (do not change it)
  type: Recreate
[%- endif %]

image:
  # Image registry
  registry: [[ component.image.registry ]]

  # Image repository
  repository: [[ component.image.repository ]]

  # Image tag
  tag: [[ component.image.tag ]]

  # Image digest
  digest: ""

  # Image pull policy
  pullPolicy: IfNotPresent

pdb:
  # Specifies whether a pod disruption budget should be created
  create: false

  # Minimum number/percentage of pods that should remain scheduled
  minAvailable: 1

  # Maximum number/percentage of pods that may be made unavailable
  # maxUnavailable: 1

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# Additional pod annotations
podAnnotations: {}

# Additional pod labels
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

# Priority class name
# priorityClassName : high-priority

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

containerPorts:
  [%- set ports = component.service.ports %]
  [%- if component.headless %]
  [%- set ports = ports + component.headless.ports %]
  [%- endif %]
  [%- for port in ports %]
  [%- if loop.index0 > 0 %]
[[ "" ]]
  [%- endif %]
  # Container port for [[ port.description ]]
  [[ port.name ]]: [[ port.number ]]
  [%- endfor %]

livenessProbe:
  # Enable liveness probe
  enabled: true

  # Delay before the liveness probe is initiated
  initialDelaySeconds: 0

  # How often to perform the liveness probe
  periodSeconds: 10

  # When the liveness probe times out
  timeoutSeconds: 1

  # Minimum consecutive failures for the liveness probe to be considered failed after having succeeded
  failureThreshold: 3

  # Minimum consecutive successes for the liveness probe to be considered successful after having failed
  successThreshold: 1

readinessProbe:
  # Enable readiness probe
  enabled: true

  # Delay before the readiness probe is initiated
  initialDelaySeconds: 0

  # How often to perform the readiness probe
  periodSeconds: 10

  # When the readiness probe times out
  timeoutSeconds: 1

  # Minimum consecutive failures for the readiness probe to be considered failed after having succeeded
  failureThreshold: 3

  # Minimum consecutive successes for the readiness probe to be considered successful after having failed
  successThreshold: 1

service:
  # Service annotations
  annotations: {}

  # Service type
  type: ClusterIP

  # Static cluster IP address or None for headless service when service type is ClusterIP
  # clusterIP: 10.43.0.100

  # Static load balancer IP address when service type is LoadBalancer
  # loadBalancerIP: 10.0.0.100

  # Source IP address ranges when service type is LoadBalancer
  # loadBalancerSourceRanges:
  #   - 10.0.0.0/24

  # External traffic routing policy when service type is LoadBalancer or NodePort
  externalTrafficPolicy: Cluster

  ports:
    [%- for port in component.service.ports %]
    [%- if loop.index0 > 0 %]
[[ "" ]]
    [%- endif %]
    # Service port for [[ port.description ]]
    [[ port.name ]]: [[ port.number ]]
    [%- endfor %]

  nodePorts: {}
    [%- for port in component.service.ports %]
    [%- if loop.index0 > 0 %]
[[ "" ]]
    [%- endif %]
    # Service node port for [[ port.description ]] when service type is LoadBalancer or NodePort
    # [[ port.name ]]: [[ 30000 + loop.index0 ]]
    [%- endfor %]

ingress:
  enabled: false

  # IngressClass that will be be used to implement the Ingress
  ingressClassName: ""

  # Ingress path type
  pathType: ImplementationSpecific

  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: [[ application.name ]].local
      paths:
        - /
  tls: []
  #  - secretName: [[ application.name ]]-tls
  #    hosts:
  #      - [[ application.name ]].local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraArgs: {}
  # name: ""

# Additional container environment variables
extraEnvVars: []
#  - name: MY-NAME
#    value: "MY-VALUE"

# Name of existing ConfigMap containing additional container environment variables
extraEnvVarsCM:

# Name of existing Secret containing additional container environment variables
extraEnvVarsSecret:
[%- if component.deployment.initContainer %]

init:
  # Init security context
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  # Init CPU/Memory resource requests/limits
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
[%- endif %]
[%- if component.headless %]

headless:
  service:
    # Headless service annotations
    annotations: {}

    ports:
      [%- for port in component.headless.ports %]
      [%- if loop.index0 > 0 %]
[[ "" ]]
      [%- endif %]
      # Headless service port for [[ port.description ]]
      [[ port.name ]]: [[ port.number ]]
      [%- endfor %]
[%- endif %]
[%- if component.persistentvolumeclaim %]

persistence:
  # Enable persistence using PVC
  enabled: false
  [%- if component.deployment.type == "deployment" %]

  # Name of an existing PVC to use
  # existingClaim: my-pvc
  [%- endif %]

  # PVC access mode
  accessMode: ReadWriteOnce

  # PVC annotations
  annotations: {}

  # PVC size
  size: 1Gi

  # PVC storage class
  # storageClass: -
[%- endif %]
[%- if component.extraValues %]

[[ component.extraValues | trim ]]
[%- endif %]
[%- endfor %]

tests:
  image:
    # Image registry
    registry: ghcr.io

    # Image repository
    repository: cowboysysop/pytest

    # Image tag
    tag: 1.0.35

    # Image digest
    digest: ""

    # Image pull policy
    pullPolicy: IfNotPresent
