apiVersion: v1
appVersion: 11
description: Full-featured vulnerability scanner
home: https://openvas.org/
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: openvas
version: 1.0.0
