python3 generator.py applications/dolibarr.yaml
python3 generator.py applications/flowise.yaml
python3 generator.py applications/kroki.yaml
python3 generator.py applications/kubebox.yaml
python3 generator.py applications/kubeview.yaml
python3 generator.py applications/lighthouse-ci.yaml
python3 generator.py applications/local-ai.yaml
python3 generator.py applications/mongo-express.yaml
python3 generator.py applications/n8n.yaml
python3 generator.py applications/ollama.yaml
python3 generator.py applications/open-webui.yaml
python3 generator.py applications/postgresql-common.yaml
python3 generator.py applications/qdrant.yaml
python3 generator.py applications/quickchart.yaml
python3 generator.py applications/vertical-pod-autoscaler.yaml
python3 generator.py applications/whoami.yaml
