{{- if and .Values.externalMinio.enabled (not .Values.externalMinio.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow-pipelines.minio.secretName" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  root-user: {{ .Values.externalMinio.rootUser | b64enc | quote }}
  root-password: {{ .Values.externalMinio.rootPassword | b64enc | quote }}
{{- end }}
