apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow-pipelines.viewer.fullname" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
