apiVersion: v2
appVersion: 1.5.0
description: Tiny Go webserver that prints os information and HTTP request to output
home: https://github.com/containous/whoami
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: whoami
sources:
  - https://github.com/containous/whoami
  - https://github.com/cowboysysop/charts/tree/master/charts/whoami
version: 2.5.2
dependencies:
  - name: common
    version: 1.7.1
    repository: https://charts.bitnami.com/bitnami/
