apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vertical-pod-autoscaler.recommender.fullname" . }}
  labels:
    {{- include "vertical-pod-autoscaler.recommender.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.recommender.replicaCount }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.recommender.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vertical-pod-autoscaler.recommender.selectorLabels" . | nindent 8 }}
        {{- with .Values.recommender.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.recommender.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "vertical-pod-autoscaler.recommender.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.recommender.podSecurityContext | nindent 8 }}
      containers:
        - name: recommender
          securityContext:
            {{- toYaml .Values.recommender.securityContext | nindent 12 }}
          image: "{{ .Values.recommender.image.repository }}:{{ .Values.recommender.image.tag }}"
          imagePullPolicy: {{ .Values.recommender.image.pullPolicy }}
          args:
            {{- range $key, $value := .Values.recommender.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 8942
              protocol: TCP
          {{- if .Values.recommender.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: http-metrics
            initialDelaySeconds: {{ .Values.recommender.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.recommender.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.recommender.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.recommender.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.recommender.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.recommender.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: http-metrics
            initialDelaySeconds: {{ .Values.recommender.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.recommender.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.recommender.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.recommender.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.recommender.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.recommender.resources | nindent 12 }}
      {{- with .Values.recommender.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.recommender.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.recommender.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
