apiVersion: v1
kind: Service
metadata:
  name: {{ include "vertical-pod-autoscaler.recommender.metrics.fullname" . }}
  labels:
    {{- include "vertical-pod-autoscaler.recommender.labels" . | nindent 4 }}
spec:
  type: {{ .Values.recommender.metrics.service.type }}
  ports:
    - port: {{ .Values.recommender.metrics.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "vertical-pod-autoscaler.recommender.selectorLabels" . | nindent 4 }}
