apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kserve.controller.fullname" . }}
  labels:
    {{- include "kserve.controller.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kserve.controller.fullname" . }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ include "kserve.controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-serving-kserve-io-v1beta1-inferenceservice
        port: {{ .Values.controller.service.port }}
    name: validate-inferenceservice.kserve.io
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ include "kserve.controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-serving-kserve-io-v1alpha1-trainedmodel
        port: {{ .Values.controller.service.port }}
    name: validate-trainedmodel.kserve.io
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - trainedmodels
    sideEffects: None
