{{- if (not .Values.jibri.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.jibri.secretName" . }}
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
type: Opaque
data:
  recorder-password: {{ default (randAlphaNum 32) .Values.jibri.recorderPassword | b64enc | quote }}
  xmpp-password: {{ default (randAlphaNum 32) .Values.jibri.xmppPassword | b64enc | quote }}
{{- end }}
