{{- if .Values.arachniEngine.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "patrowl.arachniEngine.serviceAccountName" . }}
  labels:
    {{- include "patrowl.arachniEngine.labels" . | nindent 4 }}
  {{- with .Values.arachniEngine.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
