apiVersion: v1
kind: ConfigMap
metadata:
  name: trial-templates
  labels:
    katib.kubeflow.org/component: trial-templates
    {{- include "katib.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  defaultTrialTemplate: |
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        spec:
          containers:
            - name: training-container
              image: kubeflowkatib/mxnet-mnist:v1beta1-45c5727
              command:
                - python3
                - /opt/mxnet-mnist/mnist.py
                - --batch-size=64
                - --lr=${trialParameters.learningRate}
                - --num-layers=${trialParameters.numberLayers}
                - --optimizer=${trialParameters.optimizer}
          restartPolicy: Never
  enasCPUTemplate: |
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        spec:
          containers:
            - name: training-container
              image: kubeflowkatib/enas-cnn-cifar10-cpu:v1beta1-45c5727
              command:
                - python3
                - -u
                - RunTrial.py
                - --num_epochs=1
                - "--architecture=\"${trialParameters.neuralNetworkArchitecture}\""
                - "--nn_config=\"${trialParameters.neuralNetworkConfig}\""
          restartPolicy: Never
  pytorchJobTemplate: |
    apiVersion: kubeflow.org/v1
    kind: PyTorchJob
    spec:
      pytorchReplicaSpecs:
        Master:
          replicas: 1
          restartPolicy: OnFailure
          template:
            spec:
              containers:
                - name: pytorch
                  image: kubeflowkatib/pytorch-mnist:v1beta1-45c5727
                  command:
                    - python3
                    - /opt/pytorch-mnist/mnist.py
                    - --epochs=1
                    - --lr=${trialParameters.learningRate}
                    - --momentum=${trialParameters.momentum}
        Worker:
          replicas: 2
          restartPolicy: OnFailure
          template:
            spec:
              containers:
                - name: pytorch
                  image: kubeflowkatib/pytorch-mnist:v1beta1-45c5727
                  command:
                    - python3
                    - /opt/pytorch-mnist/mnist.py
                    - --epochs=1
                    - --lr=${trialParameters.learningRate}
                    - --momentum=${trialParameters.momentum}
