apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "kubeflow.admissionWebhook.fullname" . }}
  labels:
    {{- include "kubeflow.admissionWebhook.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.admissionWebhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeflow.admissionWebhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeflow.admissionWebhook.selectorLabels" . | nindent 8 }}
        {{- if .Values.admissionWebhook.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.admissionWebhook.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
      {{- if or .Values.admissionWebhook.podAnnotations .Values.commonAnnotations }}
      annotations:
        {{- if .Values.admissionWebhook.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.admissionWebhook.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.admissionWebhook.priorityClassName }}
      priorityClassName: {{ .Values.admissionWebhook.priorityClassName | quote }}
      {{- end }}
      serviceAccountName: {{ include "kubeflow.admissionWebhook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.admissionWebhook.podSecurityContext | nindent 8 }}
      containers:
        - name: admission-webhook
          securityContext:
            {{- toYaml .Values.admissionWebhook.securityContext | nindent 12 }}
          image: "{{ .Values.admissionWebhook.image.repository }}:{{ .Values.admissionWebhook.image.tag }}"
          imagePullPolicy: {{ .Values.admissionWebhook.image.pullPolicy }}
          {{- with .Values.admissionWebhook.extraArgs }}
          args:
            {{- range $key, $value := . }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
          {{- if .Values.admissionWebhook.extraEnvVars }}
          env:
            {{- include "common.tplvalues.render" (dict "value" .Values.admissionWebhook.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if or .Values.admissionWebhook.extraEnvVarsCM .Values.admissionWebhook.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.admissionWebhook.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.admissionWebhook.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.admissionWebhook.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.admissionWebhook.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- end }}
          ports:
            - name: https
              containerPort: 4443
              protocol: TCP
          resources:
            {{- toYaml .Values.admissionWebhook.resources | nindent 12 }}
      {{- with .Values.admissionWebhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.admissionWebhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.admissionWebhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
