apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubeflow.admissionWebhook.fullname" . }}
  labels:
    {{- include "kubeflow.admissionWebhook.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kubeflow.admissionWebhook.fullname" . }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ include "kubeflow.admissionWebhook.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /apply-poddefault
        port: {{ .Values.admissionWebhook.service.port }}
    name: admission-webhook.kubeflow.org
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/created-by: {{ include "kubeflow.profiles.fullname" . }}
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
