{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowise.secretName" . }}
  labels:
    {{- include "flowise.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if and .Values.config.username .Values.config.password }}
  password: {{ .Values.config.password | b64enc | quote }}
  {{- end }}
  passphrase: {{ .Values.config.passphrase | b64enc | quote }}
{{- end }}
