{{- if and .Values.etherpad.enabled .Values.etherpad.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jitsi-meet.etherpad.serviceAccountName" . }}
  labels:
    {{- include "jitsi-meet.etherpad.labels" . | nindent 4 }}
  {{- with .Values.etherpad.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
