apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "kubeflow-pipelines.cacheServer.fullname" . }}
  labels:
    {{- include "kubeflow-pipelines.cacheServer.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.cacheServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeflow-pipelines.cacheServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeflow-pipelines.cacheServer.selectorLabels" . | nindent 8 }}
        {{- if .Values.cacheServer.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.cacheServer.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.kubeflow.enabled }}
        sidecar.istio.io/inject: "false"
        {{- end }}
        {{- if .Values.cacheServer.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.cacheServer.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.cacheServer.priorityClassName }}
      priorityClassName: {{ .Values.cacheServer.priorityClassName | quote }}
      {{- end }}
      serviceAccountName: {{ include "kubeflow-pipelines.cacheServer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.cacheServer.podSecurityContext | nindent 8 }}
      containers:
        - name: cache-server
          securityContext:
            {{- toYaml .Values.cacheServer.securityContext | nindent 12 }}
          image: "{{ .Values.cacheServer.image.repository }}:{{ .Values.cacheServer.image.tag }}"
          imagePullPolicy: {{ .Values.cacheServer.image.pullPolicy }}
          args:
            - --db_host={{ include "kubeflow-pipelines.mariadb.host" . }}
            - --db_port={{ include "kubeflow-pipelines.mariadb.port" . }}
            - --db_user={{ include "kubeflow-pipelines.mariadb.username" . }}
            - --db_password=$(MARIADB_PASSWORD)
            - --db_name={{ include "kubeflow-pipelines.mariadb.database" . }}
            - --logtostderr=true
            - --namespace_to_watch={{ .Release.Namespace }}
            {{- range $key, $value := .Values.cacheServer.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          env:
            - name: CACHE_IMAGE
              value: gcr.io/google-containers/busybox
            - name: CACHE_NODE_RESTRICTIONS
              value: "false"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kubeflow-pipelines.mariadb.secretName" . }}
                  key: {{ include "kubeflow-pipelines.mariadb.secretKeyNamePassword" . }}
            {{- if .Values.cacheServer.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.cacheServer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.cacheServer.extraEnvVarsCM .Values.cacheServer.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.cacheServer.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.cacheServer.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.cacheServer.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.cacheServer.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- end }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources:
            {{- toYaml .Values.cacheServer.resources | nindent 12 }}
          volumeMounts:
            - name: tls-secret
              mountPath: /etc/webhook/certs
              readOnly: true
      {{- with .Values.cacheServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.cacheServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.cacheServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ include "kubeflow-pipelines.cacheServer.tls.secretName" . }}
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem
