{{- if .Values.apiServer.ingress.enabled -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "dependency-track.apiServer.fullname" . }}
  labels:
    {{- include "dependency-track.apiServer.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.apiServer.ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.apiServer.ingress.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.apiServer.ingress.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.apiServer.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.apiServer.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.apiServer.ingress.tls }}
  tls:
    {{- range .Values.apiServer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.apiServer.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ $.Values.apiServer.ingress.pathType }}
            {{- end }}
            backend:
              {{- include "common.ingress.backend" (dict "serviceName" (include "dependency-track.apiServer.fullname" $) "servicePort" $.Values.apiServer.service.port "context" $) | nindent 14 }}
          {{- end }}
    {{- end }}
{{- end }}
