apiVersion: v1
kind: Service
metadata:
  name: {{ include "patrowl.manager.fullname" . }}
  labels:
    {{- include "patrowl.manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: {{ .Values.manager.service.port }}
      targetPort: http-nginx
      protocol: TCP
      name: http-nginx
  selector:
    {{- include "patrowl.manager.selectorLabels" . | nindent 4 }}
