apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "scaleway-csi.node.fullname" . }}
  labels:
    {{- include "scaleway-csi.node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "scaleway-csi.node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scaleway-csi.node.selectorLabels" . | nindent 8 }}
        {{- with .Values.node.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.node.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "scaleway-csi.node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.node.podSecurityContext | nindent 8 }}
      containers:
        - name: node
          image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}"
          imagePullPolicy: {{ .Values.node.image.pullPolicy }}
          args:
            - --endpoint=unix:///socket/csi.sock
            - --mode=node
            # -prefix string
            #     Prefix to add in block volume name
            # -v value
            #     number for the log level verbosity
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: ["/bin/sh", "-c", "rm -f /registration/csi.scaleway.com-reg.sock-reg.sock"]
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: healthz
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: healthz
          resources:
           {{- toYaml .Values.node.resources | nindent 12 }}
          volumeMounts:
            - name: socket
              mountPath: /socket
        - name: csi-node-driver-registrar
          securityContext:
            {{- toYaml .Values.node.securityContext | nindent 12 }}
          image: "{{ .Values.node.csiNodeDriverRegistrarImage.repository }}:{{ .Values.node.csiNodeDriverRegistrarImage.tag }}"
          imagePullPolicy: {{ .Values.node.csiNodeDriverRegistrarImage.pullPolicy }}
          args:
            - --csi-address=/socket/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.scaleway.com/csi.sock
            # -v value
            #     log level for V logs
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -f /registration/csi.scaleway.com-reg.sock
          resources:
           {{- toYaml .Values.node.resources | nindent 12 }}
          volumeMounts:
            - name: registry
              mountPath: /registration
            - name: socket
              mountPath: /socket
        - name: liveness-probe
          securityContext:
            {{- toYaml .Values.node.securityContext | nindent 12 }}
          image: "{{ .Values.node.livenessProbeImage.repository }}:{{ .Values.node.livenessProbeImage.tag }}"
          imagePullPolicy: {{ .Values.node.livenessProbeImage.pullPolicy }}
          args:
            - --csi-address=/socket/csi.sock
            # -health-port string
            #     TCP ports for listening healthz requests (default "9808")
            # -probe-timeout duration
            #     Probe timeout in seconds (default 1s)
            # -v value
            #     number for the log level verbosity
          resources:
           {{- toYaml .Values.node.resources | nindent 12 }}
          volumeMounts:
            - name: socket
              mountPath: /socket
      {{- with .Values.node.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.node.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.node.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: registry
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: socket
          hostPath:
            path: /var/lib/kubelet/plugins/csi.scaleway.com
            type: DirectoryOrCreate
