apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scaleway-csi.controller.fullname" . }}
  labels:
    {{- include "scaleway-csi.controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "scaleway-csi.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scaleway-csi.controller.selectorLabels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.recommender.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "scaleway-csi.controller.serviceAccountName" . }}
      {{- if .Values.controller.priorityClassName }}
      priorityClassName: {{ .Values.controller.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          args:
            - --endpoint=unix:///socket/csi.sock
            - --mode=controller
            # -prefix string
            #     Prefix to add in block volume name
            # -v value
            #     number for the log level verbosity
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # resources:
          #  {{- toYaml .Values.controller.resources | nindent 12 }}
          volumeMounts:
            - name: socket
              mountPath: /socket
        - name: liveness-probe
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.controller.livenessProbeImage.repository }}:{{ .Values.controller.livenessProbeImage.tag }}"
          imagePullPolicy: {{ .Values.controller.livenessProbeImage.pullPolicy }}
          args:
            {{- range $key, $value := .Values.controller.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          ports:
            - name: http
              containerPort: 9808
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # resources:
          #  {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: socket
          emptyDir: {}
