apiVersion: v1
kind: Service
metadata:
  # name: {{ include "scaleway-csi.controller.fullname" . }}
  name: vpa-webhook
  labels:
    {{- include "scaleway-csi.controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    # - port: {{ .Values.controller.service.port }}
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scaleway-csi.controller.selectorLabels" . | nindent 4 }}
