apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-grpc-configmap
  labels:
    {{- include "kubeflow-pipelines.mlMetadata.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  METADATA_GRPC_SERVICE_HOST: {{ include "kubeflow-pipelines.mlMetadata.fullname" . }}
  METADATA_GRPC_SERVICE_PORT: {{ .Values.mlMetadata.service.ports.grpc | quote }}
