{{- if .Values.urlvoidEngine.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "patrowl.urlvoidEngine.serviceAccountName" . }}
  labels:
    {{- include "patrowl.urlvoidEngine.labels" . | nindent 4 }}
  {{- with .Values.urlvoidEngine.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
