{{- if .Values.kubeflow.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kserve.modelsWebApp.fullname" . }}
  labels:
    {{- include "kserve.modelsWebApp.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.kubeflow.gatewayName }}
  http:
    - match:
        - uri:
            prefix: /models/
      route:
        - destination:
            host: {{ include "kserve.modelsWebApp.fullname" . }}
            port:
              number: {{ .Values.modelsWebApp.service.port }}
      rewrite:
        uri: /
{{- end }}
