{{- if .Values.[[ component.name | to_lower_camel ]].ingress.enabled -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "[[ application.name ]].[[ component.name | to_lower_camel ]].fullname" . }}
  labels:
    {{- include "[[ application.name ]].[[ component.name | to_lower_camel ]].labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.[[ component.name | to_lower_camel ]].ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.[[ component.name | to_lower_camel ]].ingress.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.[[ component.name | to_lower_camel ]].ingress.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.[[ component.name | to_lower_camel ]].ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.[[ component.name | to_lower_camel ]].ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.[[ component.name | to_lower_camel ]].ingress.tls }}
  tls:
    {{- range .Values.[[ component.name | to_lower_camel ]].ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.[[ component.name | to_lower_camel ]].ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ $.Values.[[ component.name | to_lower_camel ]].ingress.pathType }}
            {{- end }}
            backend:
              {{- include "common.ingress.backend" (dict "serviceName" (include "[[ application.name ]].[[ component.name | to_lower_camel ]].fullname" $) "servicePort" $.Values.[[ component.name | to_lower_camel ]].service.ports.http "context" $) | nindent 14 }}
          {{- end }}
    {{- end }}
{{- end }}
