apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" . }}
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jvb.replicaCount }}
  selector:
    matchLabels:
      {{- include "jitsi-meet.jvb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.jvb.selectorLabels" . | nindent 8 }}
        {{- with .Values.jvb.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/jvb/secret.yaml") . | sha256sum }}
        {{- with .Values.jvb.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jitsi-meet.jvb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jvb.podSecurityContext | nindent 8 }}
      containers:
        - name: jvb
          securityContext:
            {{- toYaml .Values.jvb.securityContext | nindent 12 }}
          image: "{{ .Values.jvb.image.repository }}:{{ .Values.jvb.image.tag }}"
          imagePullPolicy: {{ .Values.jvb.image.pullPolicy }}
          env:
            - name: XMPP_SERVER
              value: {{ include "jitsi-meet.prosody.fullname" . }}
            - name: XMPP_AUTH_DOMAIN
              value: {{ .Values.xmpp.authDomain | quote }}
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: {{ .Values.xmpp.internalMucDomain | quote }}
            - name: JVB_AUTH_USER
              value: {{ .Values.jvb.authUser | quote }}
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jitsi-meet.jvb.secretName" . }}
                  key: auth-password
            - name: JVB_BREWERY_MUC
              value: {{ .Values.jvb.breweryMuc | quote }}
          ports:
            - name: metrics
              containerPort: 8942
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          # readinessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: metrics
          resources:
            {{- toYaml .Values.jvb.resources | nindent 12 }}
      {{- with .Values.jvb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.jvb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jvb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
