apiVersion: v1
kind: Service
metadata:
  name: {{ include "[[ application.name ]].headless.fullname" . }}
  labels:
    {{- include "[[ application.name ]].labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.headless.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.headless.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.headless.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    [%- for port in component.headless.ports %]
    - port: {{ .Values.headless.service.ports.[[ port.name ]] }}
      targetPort: [[ port.name ]]
      protocol: TCP
      name: [[ port.name ]]
    [%- endfor %]
  publishNotReadyAddresses: true
  selector:
    {{- include "[[ application.name ]].selectorLabels" . | nindent 4 }}
