[%- if component.name == application.name -%]
[%- set component_values_path = "." %]
[%- else -%]
[%- set component_values_path = component.name | to_lower_camel %]
[%- set component_values_path = "." + component_values_path + "." %]
[%- endif -%]
[%- if component.optional -%]
{{- if .Values[[ component_values_path ]]enabled }}
[%- endif %]
apiVersion: v1
kind: Service
metadata:
  name: {{ include "[[ application.name ]][[ component_values_path ]]metrics.fullname" . }}
  labels:
    {{- include "[[ application.name ]][[ component_values_path ]]labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values[[ component_values_path ]]metrics.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values[[ component_values_path ]]metrics.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values[[ component_values_path ]]metrics.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values[[ component_values_path ]]metrics.service.type }}
  {{- if and (eq .Values[[ component_values_path ]]metrics.service.type "ClusterIP") .Values[[ component_values_path ]]metrics.service.clusterIP }}
  clusterIP: {{ .Values[[ component_values_path ]]metrics.service.clusterIP }}
  {{- end }}
  ports:
    [%- for port in component.metrics.ports %]
    - port: {{ .Values[[ component_values_path ]]metrics.service.ports.[[ port.name ]] }}
      targetPort: [[ port.nameIstio or port.name ]]
      protocol: TCP
      name: [[ port.nameIstio or port.name ]]
    [%- endfor %]
  selector:
    {{- include "[[ application.name ]][[ component_values_path ]]selectorLabels" . | nindent 4 }}
[%- if component.optional %]
{{- end }}
[%- endif %]
