{{- if and .Values.veleroBackups.enabled .Values.veleroBackups.hourly.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "[[ application.name ]].fullname" . }}-hourly
  namespace: {{ default (include "common.names.namespace" .) .Values.veleroBackups.namespace | quote }}
  labels:
    {{- include "[[ application.name ]].labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.veleroBackups.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.veleroBackups.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.veleroBackups.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  schedule: {{ .Values.veleroBackups.hourly.minute }} * * * *
  template:
    includedNamespaces:
      - {{ include "common.names.namespace" . | quote }}
    {{- if .Values.veleroBackups.backupLocation }}
    storageLocation: {{ .Values.veleroBackups.backupLocation }}
    {{- end }}
    {{- if .Values.veleroBackups.snapshotLocation }}
    volumeSnapshotLocations:
      - {{ .Values.veleroBackups.snapshotLocation }}
    {{- end }}
    ttl: {{ mul .Values.veleroBackups.hourly.retention }}h
    snapshotMoveData: true
{{- end }}
