[% if component.name == application.name %]
[% set component_values_path = "." %]
[% else %]
[% set component_values_path = component.name | to_lower_camel %]
[% set component_values_path = "." + component_values_path + "." %]
[% endif %]
[% if component.optional %]
{{- if .Values[[ component_values_path ]]enabled }}
[% endif %]
{{- if and (.Capabilities.APIVersions.Has "autoscaling.k8s.io/v1/VerticalPodAutoscaler") .Values[[ component_values_path ]]autoscaling.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "[[ application.name ]][[ component_values_path ]]fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "[[ application.name ]][[ component_values_path ]]labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values[[ component_values_path ]]autoscaling.vpa.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values[[ component_values_path ]]autoscaling.vpa.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: [[ component.name ]]
      {{- with .Values[[ component_values_path ]]autoscaling.vpa.controlledResources }}
      controlledResources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values[[ component_values_path ]]autoscaling.vpa.maxAllowed }}
      maxAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values[[ component_values_path ]]autoscaling.vpa.minAllowed }}
      minAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  targetRef:
    [% if component.deployment.type == "deployment" %]
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    [% elif component.deployment.type == "statefulset" %]
    apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
    kind: StatefulSet
    [% endif %]
    name: {{ include "[[ application.name ]][[ component_values_path ]]fullname" . }}
  {{- if .Values[[ component_values_path ]]autoscaling.vpa.updatePolicy }}
  updatePolicy:
    {{- with .Values[[ component_values_path ]]autoscaling.vpa.updatePolicy.updateMode }}
    updateMode: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
