apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi-meet.jicofo.fullname" . }}
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.jicofo.replicaCount }}
  selector:
    matchLabels:
      {{- include "jitsi-meet.jicofo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jitsi-meet.jicofo.selectorLabels" . | nindent 8 }}
        {{- with .Values.jicofo.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.jicofo.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jitsi-meet.jicofo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jicofo.podSecurityContext | nindent 8 }}
      containers:
        - name: jicofo
          securityContext:
            {{- toYaml .Values.jicofo.securityContext | nindent 12 }}
          image: "{{ .Values.jicofo.image.repository }}:{{ .Values.jicofo.image.tag }}"
          imagePullPolicy: {{ .Values.jicofo.image.pullPolicy }}
          args:
            - --client-ca-file=/tls-secret/ca.crt
            - --tls-cert-file=/tls-secret/tls.crt
            - --tls-private-key=/tls-secret/tls.key
            {{- range $key, $value := .Values.jicofo.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: metrics
              containerPort: 8944
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.jicofo.resources | nindent 12 }}
          volumeMounts:
            - name: tls-secret
              mountPath: /tls-secret
              readOnly: true
      {{- with .Values.jicofo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.jicofo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.jicofo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ include "jitsi-meet.jicofo.tls.secretName" . }}
