apiVersion: v2
appVersion: 0.9.0
description: Terminal and Web console for Kubernetes
home: https://github.com/astefanutti/kubebox
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kubebox
sources:
  - https://github.com/astefanutti/kubebox
  - https://github.com/cowboysysop/charts/tree/master/charts/kubebox
version: 2.6.2
dependencies:
  - name: common
    version: 1.7.1
    repository: https://charts.bitnami.com/bitnami/
