apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vertical-pod-autoscaler.updater.fullname" . }}
  labels:
    {{- include "vertical-pod-autoscaler.updater.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.updater.replicaCount }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.updater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vertical-pod-autoscaler.updater.selectorLabels" . | nindent 8 }}
        {{- with .Values.updater.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.updater.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "vertical-pod-autoscaler.updater.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.updater.podSecurityContext | nindent 8 }}
      containers:
        - name: updater
          securityContext:
            {{- toYaml .Values.updater.securityContext | nindent 12 }}
          image: "{{ .Values.updater.image.repository }}:{{ .Values.updater.image.tag }}"
          imagePullPolicy: {{ .Values.updater.image.pullPolicy }}
          args:
            {{- range $key, $value := .Values.updater.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8943
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.updater.resources | nindent 12 }}
      {{- with .Values.updater.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.updater.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.updater.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
