{{- if .Values.recommender.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scaleway-csi.recommender.serviceAccountName" . }}
  labels:
    {{- include "scaleway-csi.recommender.labels" . | nindent 4 }}
  {{- with .Values.recommender.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
