apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "faraday.fullname" . }}
  labels:
    {{- include "faraday.labels" . | nindent 4 }}
data:
  lighthouserc.json: |
    {
      "ci": {
        "server": {
          "port": 9001,
          "storage": {
            "storageMethod": "sql",
            "sqlDialect": "sqlite",
            "sqlDatabasePath": "/data/lhci.db"
          },
          "psiCollectCron": {
            "psiApiKey": {{ .Values.psiCollectCron.psiApiKey | quote }},
            "sites": {{ .Values.psiCollectCron.sites | toJson }}
          },
          "deleteOldBuildsCron": {{ .Values.deleteOldBuildsCron | toJson }}
        }
      }
    }
