apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubeflow.kfservingController.fullname" . }}
  labels:
    {{- include "kubeflow.kfservingController.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kubeflow.kfservingController.fullname" . }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ include "kubeflow.kfservingController.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-serving-kubeflow-org-v1alpha2-inferenceservice
        port: {{ .Values.kfservingController.service.port }}
    name: mutate-inferenceservice-v1alpha2.kfserving-controller.kubeflow.org
    rules:
      - apiGroups:
          - serving.kubeflow.org
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ include "kubeflow.kfservingController.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-serving-kubeflow-org-v1beta1-inferenceservice
        port: {{ .Values.kfservingController.service.port }}
    name: mutate-inferenceservice-v1beta1.kfserving-controller.kubeflow.org
    rules:
      - apiGroups:
          - serving.kubeflow.org
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ include "kubeflow.kfservingController.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-pods
        port: {{ .Values.kfservingController.service.port }}
    name: mutate-pod.kfserving-controller.kubeflow.org
    namespaceSelector:
      matchLabels:
        serving.kubeflow.org/inferenceservice: enabled
    objectSelector:
      matchExpressions:
        - key: serving.kubeflow.org/inferenceservice
          operator: Exists
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    sideEffects: None
