apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubeflow.kfservingController.fullname" . }}
  labels:
    {{- include "kubeflow.kfservingController.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kubeflow.kfservingController.fullname" . }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: {{ include "kubeflow.kfservingController.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-serving-kubeflow-org-v1alpha1-trainedmodel
        port: {{ .Values.kfservingController.service.port }}
    name: validate-trainedmodel.kfserving-controller.kubeflow.org
    rules:
      - apiGroups:
          - serving.kubeflow.org
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - trainedmodels
    sideEffects: None
