apiVersion: v2
appVersion: 1.2.14
description: Drag & drop UI to build your customized LLM flow
home: https://flowiseai.com/
icon: https://avatars.githubusercontent.com/u/128289781
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: flowise
sources:
  - https://github.com/FlowiseAI/Flowise
  - https://github.com/cowboysysop/charts/tree/master/charts/flowise
version: 1.0.1
dependencies:
  - name: common
    version: 2.5.0
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.19"
